{% set name = "llama-index-cli" %}
{% set version = "0.5.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_cli-{{ version }}.tar.gz
  sha256: 630885bbe33d43955d49abe034bd77507f6c722bb394cc2c4845deb6027d2ff4

build:
  entry_points:
    - llamaindex-cli = llama_index.cli.command_line:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.13.0,<0.15
    - llama-index-embeddings-openai >=0.5.0,<0.6
    - llama-index-llms-openai >=0.6.0,<0.7

test:
  imports:
    - llama_index.cli
  commands:
    - pip check
    - llamaindex-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: llama-index cli
  home: https://docs.llamaindex.ai/en/stable/getting_started/starter_tools/rag_cli/
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-cli

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
