{% set name = "llama-index-cli" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_cli-{{ version }}.tar.gz
  sha256: c60c5becc412b9d5d4eb58cbb8efd41363e45cb866f21a65c887f8fee9276443

build:
  entry_points:
    - llamaindex-cli = llama_index.cli.command_line:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.12.0,<0.13.0
    - llama-index-embeddings-openai >=0.3.0,<0.4.0
    - llama-index-llms-openai >=0.4.0,<0.5.0

test:
  imports:
    - llama_index.cli
  commands:
    - pip check
    - llamaindex-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: llama-index cli
  home: https://docs.llamaindex.ai/en/stable/getting_started/starter_tools/rag_cli/
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-cli

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
