{% set name = "llama-index-cli" %}
{% set version = "0.4.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_cli-{{ version }}.tar.gz
  sha256: dae8183a10551bbd89686b94ed294a6cf44633c3dd6285c4f991c85031b7a55f

build:
  entry_points:
    - llamaindex-cli = llama_index.cli.command_line:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.12.0,<0.13
    - llama-index-embeddings-openai >=0.3.1,<0.4
    - llama-index-llms-openai >=0.4.0,<0.5

test:
  imports:
    - llama_index.cli
  commands:
    - pip check
    - llamaindex-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: llama-index cli
  home: https://docs.llamaindex.ai/en/stable/getting_started/starter_tools/rag_cli/
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-cli

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
